[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DUSER_SETUP_LOADED
  -DST7796_DRIVER
  -DTFT_WIDTH=480
  -DTFT_HEIGHT=272
  -DTFT_MISO=13
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=14
  -DTFT_RST=9
  -DTFT_BL=38
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DLOAD_FONT6
  -DLOAD_FONT7
  -DLOAD_GFXFF
  -DSMOOTH_FONT

lib_deps =
  lvgl/lvgl@^9.2.2
  bodmer/TFT_eSPI@^2.5.43